version: '3.7'
services:
  web:
    container_name: dataviz6
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - './:/usr/local/apache2/htdocs/'
